---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: metakube-all
  namespace: default
spec:
  commonName: ""
  dnsNames:
  - '*.<YOUR_NAME>.metakube.org'
  secretName: metakube-tls-certs
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
