---
apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    app: mysql-app
spec:
  ports:
    - port: 3306
  selector:
    app: mysql-app
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: mysql-app
spec:
<<<<<<< HEAD
  storageClassName: sys11-quobyte 
=======
>>>>>>> 76ca331b4a4c1ad4152bb99ba8f97d37c570d662
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: mysql-app
  labels:
    app: mysql-app
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql-app
    spec:
      containers:
<<<<<<< HEAD
      - image: mysql:5.7 
=======
      - image: percona
>>>>>>> 76ca331b4a4c1ad4152bb99ba8f97d37c570d662
        args:
          - "--ignore-db-dir=lost+found"
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-root-password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-database
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-user
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: mysql-password
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pv-claim
