apiVersion: v1  
kind: Secret  
metadata:  
  name: mysql-secrets
type: Opaque  
data:  
  mysql-root-password: UGhvNXdlZVBoOVJhaDdhZQ== 
  mysql-user: c2hvcHdhcmU= 
  mysql-database: c2hvcHdhcmU=
  mysql-password: UmEyT3ppMW9ocjdqYWlRdTFFaQ==
