kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: prometheus
  namespace: monitoring
spec:
  tls:
    - hosts:
        - prometheus.<YOUR_NAME>.plgrnd.be
  rules:
    - host: prometheus.<YOUR_NAME>.plgrnd.be
      http:
        paths:
          - path: /
            backend:
              serviceName: prometheus-k8s
              servicePort: 9090
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: grafana
  namespace: monitoring
spec:
  tls:
    - hosts:
        - grafana.<YOUR_NAME>.plgrnd.be
  rules:
    - host: grafana.<YOUR_NAME>.plgrnd.be
      http:
        paths:
          - path: /
            backend:
              serviceName: grafana
              servicePort: 3000
---
kind: Ingress
apiVersion: extensions/v1beta1
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  tls:
    - hosts:
        - alertmanager.<YOUR_NAME>.plgrnd.be
  rules:
    - host: alertmanager.<YOUR_NAME>.plgrnd.be
      http:
        paths:
          - path: /
            backend:
              serviceName: alertmanager-main
              servicePort: 9093
