---
- hosts: all
  user: ubuntu
  become: yes
  become_method: sudo
  gather_facts: false
  pre_tasks:
    - name: PreTask install python for ansible
      raw: bash -c "test -e /usr/bin/python3 || (apt -qqy update && apt install -qqy python3-minimal)"
      register: output
      changed_when:
      - output.stdout != ""
      - output.stdout != "\r\n"

- hosts: all
  user: ubuntu
  become: yes
  become_method: sudo
  roles:
  - common
  - kubeadm-cluster
  - upgrade-packages
