image:
  registry: docker.io
  repository: bitnami/external-dns
  tag: 0.5.17-debian-9-r0
  pullPolicy: IfNotPresent

## This controls which types of resource external-dns should 'watch' for new
## DNS entries.
sources:
  - service
  - ingress

## The DNS provider where the DNS records will be created (options: aws, google, inmemory, azure, rfc2136 )
provider: aws

# AWS Access keys to inject as environment variables
aws:
  credentials:
    secretKey: "CHANGEME"
    accessKey: "CHANGEME"
    mountPath: "/.aws"
    region: "eu-central-1"
    zoneType: "public"
    batchChangeSize: 1000

## Limit possible target zones by domain suffixes (optional)
domainFilters: [metakube.org]
## Limit possible target zones by zone id (optional)
zoneIdFilters: []
# Filter sources managed by external-dns via annotation using label selector semantics (default: all sources)
annotationFilter: ""
## Adjust the interval for DNS updates
interval: "1m"

# Registry to use for ownership (txt or noop)
registry: "txt"

# When using the TXT registry, a name that identifies this instance of ExternalDNS
txtOwnerId: "CHANGEME"

## Modify how DNS records are sychronized between sources and providers (options: sync, upsert-only )
policy: sync

# Verbosity of the logs (options: panic, debug, info, warning, error, fatal)
logLevel: info

## CPU and Memory limit and request for external-dns
resources:
  limits:
    memory: 50Mi
  requests:
    memory: 50Mi
    cpu: 10m

rbac:
  create: true
  apiVersion: v1beta1
