---
- name: Add docker apt signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 0EBFCD88
    state: present

- name: Add kubernetes APT signing key
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 6A030B21BA07F4FB
    state: present

- name: Add docker repository
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

- name: Add Kubernetes repository
  apt_repository:
    repo: "deb http://apt.kubernetes.io/ kubernetes-{{ ubuntu_release | default('xenial') }} main"
    state: present

- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
    force_apt_get: true

- name: Pin Kubeadm Apt Packages  
  template:
    src: "kubeadm-apt.j2"
    dest: "/etc/apt/preferences.d/kubeadm"  
    owner: root
    group: root
    mode: 0644

- name: Pin docker APT package
  template:
    src: "docker-apt.j2"
    dest: "/etc/apt/preferences.d/docker"
    owner: root
    group: root
    mode: 0644

- name: Install docker kubeadm and cni plugins
  apt:
    name:
      - docker-ce={{ docker_version }}-{{ ansible_distribution_release }}
      - python3-docker
      - kubelet={{ kubernetes_version }}-00
      - kubeadm={{ kubernetes_version }}-00
      - kubectl={{ kubernetes_version }}-00
      - kubernetes-cni={{ kubernetes_cni_version }}-00
    state: present
    cache_valid_time: 3600
    update_cache: yes
    force_apt_get: yes
