# https://kubernetes.io/docs/admin/addons/
# network plugin: flannel weave calico if you use flannel add pod_network_cidr
network_plugin: flannel
pod_network_cidr: 10.244.0.0/16

# kubeadm Version
kubernetes_version: 1.17.1

# kubernetes cni version
kubernetes_cni_version: 0.7.5

# docker version
docker_version: 5:19.03.4~3-0~ubuntu

# Maximum size of docker log files in megabyte
docker_max_log_size: 250m

# Maximum number of docker log files
docker_max_log_files: 5

# cgroup driver used by docker and the kubelet
cgroup_driver: systemd

# daemon set to create network pods and rbac for kubernetes
network_addon_url: https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

# Configure cloud provider openstack or aws
cloud_provider: aws

# Master load balancer address. IP or cname of the load balancer
# load_balancer_addr:
