---

- name: update /etc/hostname file
  copy:
    content: "{{ inventory_hostname }}{% if hostname_postfix | length > 0 %}-{{ hostname_postfix }}{% endif %}"
    dest: /etc/hostname

- name: Set the hostname
  hostname:
    name: "{{ inventory_hostname }}{% if hostname_postfix | length > 0 %}-{{ hostname_postfix }}{% endif %}"

- name: update /etc/hosts file
  blockinfile:
    dest: /etc/hosts
    content: "{{ lookup('template', 'templates/hosts.j2') }}"
    state: present

- name: create symlink /etc/localtime
  file:
    src: /usr/share/zoneinfo/Europe/Berlin
    dest: /etc/localtime
    owner: root
    group: root
    state: link

- name: Reconfigure timezone
  shell: DEBIAN_FRONTEND=noninteractive dpkg-reconfigure -f noninteractive tzdata
  changed_when: 0

- name: Push root vimrc
  template:
    src: vimrc.j2
    dest: "{{ ansible_env.HOME }}/.vimrc"
  changed_when: 0

- name: Push ansible user vimrc
  template:
    src: vimrc.j2
    dest: "/home/{{ ansible_user }}/.vimrc"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  when: ansible_user !="root"

- name: Set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic
  changed_when: 0

- name: modifiy open file limit (limits.conf)
  template:
    src: limits.conf.j2
    dest: "/etc/security/limits.conf"
    owner: "root"
    group: "root"

- name: modifiy open file limit systemd.conf
  lineinfile:
    dest: /etc/systemd/system.conf
    regexp: "^#?DefaultLimitNOFILE"
    line: "DefaultLimitNOFILE={{ open_file_limit | default ('65535') }}"
    state: present
  notify: reload systemd
