---
- name: Install tools and system packages
  apt:
    name:
      - bash-completion
      - curl
      - dbus
      - git
      - htop
      - iftop
      - iotop
      - language-pack-en
      - net-tools
      - python3-pycurl
      - software-properties-common
      - tmux
      - unzip
      - vim
    state: present
    update_cache: yes
    cache_valid_time: 3600
    install_recommends: no
    force_apt_get: yes
