---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    dns01:
      providers:
      - name: digitalocean
        digitalocean:
          tokenSecretRef:
            name: digitalocean-dns
            key: access-token
    email: admin@metakube.de
    privateKeySecretRef:
      name: letsencrypt-acme-account-key
    server: https://acme-v02.api.letsencrypt.org/directory
