---
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: plgrnd-all
  namespace: default 
spec:
  acme:
    config:
    - domains:
      - '*.plgrnd.be'
      dns01:
        provider: digitalocean
  commonName: ""
  dnsNames:
      - '*.plgrnd.be'
  secretName: plgrnd-tls-certs 
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
